version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    image: "pokedex/react:1.0"
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start